apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["sh", "-c", "echo Container 1 running; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data
  - name: container-2
    image: busybox
    command: ["sh", "-c", "echo Container 2 running; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data
  volumes:
  - name: shared-storage
    emptyDir: {}
