apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"  # Sleep for an hour to keep the pod running